server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hibernatecoredb
    username: root
    password: 1234567890
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

